okvqa:
  txt_path: xxx\okvqa\okvqa_train.json
  img_path: xxx\data\train2014
  cap_path: asserts/okvqa/captions_okvqa.json
  tag_path: asserts/okvqa/tags_okvqa.json
  ans_path: asserts/okvqa/candidates_okvqa.json