BERT_VERSION: models/bert-large-uncased
MAX_TOKEN: 32

CLIP_VERSION: RN50x64

ANS_DICT_PATH: asserts/okvqa/answer_dict_okvqa.json

MCAN_PATH: models/mcan/epoch_6.pkl
IMG_RESOLUTION: 512
IMG_FEAT_GRID: 16
FF_SIZE: 4096
FLAT_OUT_SIZE: 2048
IMG_FEAT_SIZE: 4096
HIDDEN_SIZE: 1024
LANG_FEAT_SIZE: 1024
LAYER: 6
ARCH_CEIL: {
  enc: ['SA', 'FFN'],
  dec: ['SA_v', 'GA', 'FFN'],
}
DROPOUT_R: 0.1
MULTI_HEAD: 8
FLAT_MLP_SIZE: 1024
FLAT_GLIMPSES: 1


ANS_SIZE: 4477